### ISSUE TITLE
Race condition between AlarmReqAgent::stop and AlarmReqAgent::alarm_request

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/clearwater-snmp-handlers#127]
I inadvertently made alarms be retransmitted more often in UT, and saw the following crash:

```
Thread 8 (Thread 0x2ba06a015700 (LWP 869)):
#0  0x00002ba068ee0b99 in __libc_waitpid (pid=946, stat_loc=stat_loc@entry=0x2ba06a014120, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00002ba068e662e2 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00000000004c3694 in test_main_handle_signal (xiSigNum=11) at ut/test_main.cpp:117
#3  <signal handler called>
#4  __GI___pthread_mutex_lock (mutex=0x2ba06c003320) at ../nptl/pthread_mutex_lock.c:66
#5  0x00000000004d21bc in eventq<std::vector<std::string, std::allocator<std::string> > >::push_noblock (this=0x0, item=...) at modules/cpp-common/include/eventq.h:239
#6  0x00000000004c5561 in AlarmReqAgent::alarm_request (this=0xbd1c68 <AlarmReqAgent::_instance>, req=...) at modules/cpp-common/src/alarm.cpp:312
#7  0x00000000004c51b1 in AlarmState::issue (this=0x12a5e40) at modules/cpp-common/src/alarm.cpp:70
#8  0x00000000004c5efd in BaseAlarm::reraise_last_state (this=0x12a5e30) at modules/cpp-common/src/alarm.cpp:112
#9  0x00000000004c6d10 in AlarmManager::reraise_alarms (this=0xbd1ce0 <AlarmManager::_instance>) at modules/cpp-common/src/alarm.cpp:234
#10 0x00000000004c685c in AlarmManager::reraise_alarms_function (data=0xbd1ce0 <AlarmManager::_instance>) at modules/cpp-common/src/alarm.cpp:201
#11 0x00002ba066c28182 in start_thread (arg=0x2ba06a015700) at pthread_create.c:312
#12 0x00002ba068f1a47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

This is because one thread can call AlarmReqAgent::stop (destroying the event queue) but another can call AlarmReqAgent::alarm_request (trying to use it and crashing).

We'd never hit this live (or only on shutdown) because we don't routinely call AlarmReqAgent::stop - it's just a UT thing.

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/cpp-common/pull/526
