### ISSUE TITLE
Live tests don't run against an all-in-one node without SNMP=N

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/clearwater-snmp-handlers#18]
SNMP stats are enabled (as the clearwater-snmp-handlers-* are installed). Running the tests gives the output: 
```
Basic Call - Mainline (TCP) - (6515550540, 6515550234) Failed
  SNMP::RequestTimeout thrown:
   - host 93.184.216.119 not responding
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/snmp-1.1.1/lib/snmp/manager.rb:266:in `get_next'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/snmp-1.1.1/lib/snmp/manager.rb:426:in `block in walk'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/snmp-1.1.1/lib/snmp/manager.rb:425:in `loop'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/snmp-1.1.1/lib/snmp/manager.rb:425:in `walk'
     - /home/ubuntu/clearwater-live-test/lib/test-definition.rb:413:in `block in verify_snmp_stats'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/snmp-1.1.1/lib/snmp/manager.rb:205:in `open'
     - /home/ubuntu/clearwater-live-test/lib/test-definition.rb:412:in `verify_snmp_stats'
     - /home/ubuntu/clearwater-live-test/lib/test-definition.rb:264:in `run'
     - /home/ubuntu/clearwater-live-test/lib/test-definition.rb:136:in `block (2 levels) in run_all'
     - /home/ubuntu/clearwater-live-test/lib/test-definition.rb:129:in `collect'
     - /home/ubuntu/clearwater-live-test/lib/test-definition.rb:129:in `block in run_all'
     - /home/ubuntu/clearwater-live-test/lib/test-definition.rb:127:in `times'
     - /home/ubuntu/clearwater-live-test/lib/test-definition.rb:127:in `run_all'
     - /home/ubuntu/clearwater-live-test/lib/live-test.rb:48:in `run_tests'
     - /home/ubuntu/clearwater-live-test/Rakefile:39:in `block in <top (required)>'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/task.rb:228:in `call'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/task.rb:223:in `each'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
     - /home/ubuntu/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:101:in `each'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:73:in `block in run'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/bin/rake:19:in `load'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/bin/rake:19:in `<main>'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `<main>'
```

Workaround is to add SNMP=N!

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/clearwater-live-test/pull/93
